### ISSUE TITLE
Version number of App shows 1.2 instead of 1.3...

### ISSUE THREAD

**Issue by everetteallen** [rtrouton/First_Boot_Package_Install_Generator#2]
![screen shot 2016-02-01 at 11 37 22 am](https://cloud.githubusercontent.com/assets/5263924/12723717/95251d40-c8d8-11e5-9b4f-950ae6ab5f87.png)
Is this really 1.3 and the build number just did not get set?

**Comment by Dials-Mavis** [comment]
I'm not seeing this issue after upgrading the application with the supplied installer package

**Comment by rtrouton** [comment]
Current version is showing as 1.5 and appears to normally display version number. Closing issue.

![screen shot 2016-06-27 at 7 58 58 am](https://cloud.githubusercontent.com/assets/618055/16378996/0ebed376-3c3d-11e6-81cb-3c71d0aae7a8.png)
