### ISSUE TITLE
Can't modif

### ISSUE THREAD

**Issue by chillus** [rtrouton/First_Boot_Package_Install_Generator#3]
Hello
When I do the following to bypass network check, get error "unable to execute script Applescript"

> 1) Download/install the app, browse the package contents, and copy "installer_build_components.tgz" into a temporary directory somewhere. Extract the contents of "installer_build_components.tgz"
> 
> 2) Edit "private/user/firstbootpackageinstall_noswupdates.sh". Comment out or delete lines 84-114 (the section that checks for a network connection)
> 
> 3) Recompress that directory (e.g. "tar -cvzf installer_build_components.tgz installer_build_components")
> 
> 4) Replace the "installer_build_components.tgz" file in the package contents with the one you just created.

Do you have an other way to bypass this check action ?

Tx

**Comment by rtrouton** [comment]
Nope. If you want to modify how this application works, the responsibility for making it work afterwards is on you as the person making the modifications.
