### ISSUE TITLE
FR: Distribution packages missing product id, necessary for startosinstall inclusion

### ISSUE THREAD

**Issue by poundbangbash** [rtrouton/First_Boot_Package_Install_Generator#4]
Documented at https://managingosx.wordpress.com/2017/11/17/customized-high-sierra-install-issues-and-workarounds/ distribution-style packages need to have a unique product id included in the distribution file for it to work with `startosinstall`'s `--installpackage` option. Without a product id the package is not included in the output of that tool.

This FR is to ask to include a product ID when building a distribution pkg.

Example:
Add `<product id="com.foo.bar.pkg" version="1.0"/>` to the distribution. This is done as part of the `productbuild` binary as `productbuild --identifier com.foo.bar.pkg`.

```
<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="1">
    <pkg-ref id="com.foo.bar.pkg">
        <bundle-version/>
    </pkg-ref>
    <options customize="never" require-scripts="false"/>
    <choices-outline>
        <line choice="default">
            <line choice="com.foo.bar.pkg"/>
        </line>
    </choices-outline>
    <choice id="default"/>
    <choice id="com.foo.bar.pkg" visible="false">
        <pkg-ref id="com.foo.bar.pkg"/>
    </choice>
    <pkg-ref id="com.foo.bar.pkg" version="1.0" onConclusion="none" installKBytes=“3">#FooBar.pkg</pkg-ref>
    <product id="com.foo.bar.pkg" version="1.0"/>
</installer-gui-script>
```

**Comment by rtrouton** [comment]
First Boot Package Install Generator.app 1.7 now adds product identifiers by default. The product identifiers will be the user-selected `Package Identifier` followed by the `Version Identifier`.

<img width="420" alt="screen shot 2017-11-21 at 2 21 13 pm" src="https://user-images.githubusercontent.com/618055/33106999-162dd300-cf03-11e7-9f6e-55fd22ff673b.png">

<img width="420" alt="screen shot 2017-11-21 at 2 21 19 pm" src="https://user-images.githubusercontent.com/618055/33107020-382e0290-cf03-11e7-83d5-e9fe135e66c7.png">

![screen shot 2017-11-21 at 2 22 03 pm](https://user-images.githubusercontent.com/618055/33107024-3cb8f1ee-cf03-11e7-933c-d8bc5d941a5d.png)


First Boot Package Install Generator.app 1.7 can be downloaded via the link below:

[https://github.com/rtrouton/First_Boot_Package_Install_Generator/releases/tag/1.7](https://github.com/rtrouton/First_Boot_Package_Install_Generator/releases/tag/1.7)
